'use strict';

const fs = require('fs');
const path = require('path');
const { c } = require('./constants');
const { detectStack } = require('./detectors');

/**
 * Install a Git pre-commit hook that enforces OpenGuild verification invariants.
 *
 * @param {string} projectDir - Workspace directory.
 * @returns {boolean} True if installed successfully.
 */
function installPreCommitHook(projectDir) {
  const gitDir = path.join(projectDir, '.git');
  if (!fs.existsSync(gitDir)) {
    console.error(`${c.red}✖ No .git repository found in ${projectDir}.${c.reset}`);
    console.error('  Run "git init" first, then re-run this command.');
    return false;
  }

  const hooksDir = path.join(gitDir, 'hooks');
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  let files = [];
  try {
    files = fs.readdirSync(projectDir);
  } catch {
    files = [];
  }
  const stack = detectStack(files, projectDir);

  const hookScript = `#!/usr/bin/env sh
# OpenGuild Deterministic Pre-Commit Invariants
# Generated by antigravity-guild

# Cross-platform compatibility shim: On Windows environments (e.g. GitHub Desktop, Git GUI, MSYS),
# bash may not be on the PATH, and Node CLI tools (npm, npx, pnpm, yarn, bun) are shell scripts
# starting with '#!/usr/bin/env bash'. When bash is unavailable, forward to native .cmd wrappers.
if ! command -v bash >/dev/null 2>&1; then
  npm() { npm.cmd "$@"; }
  npx() { npx.cmd "$@"; }
  pnpm() { pnpm.cmd "$@"; }
  yarn() { yarn.cmd "$@"; }
  bun() { bun.cmd "$@"; }
fi

echo "⚡ [OpenGuild] Enforcing pre-commit verification invariants..."

echo "🧪 Running Test Suite: ${stack.testCmd.replace(/"/g, '\\"')}"
${stack.testCmd}
if [ $? -ne 0 ]; then
  echo "✖ Tests failed. Commit aborted."
  exit 1
fi

echo "🔍 Running Linter: ${stack.lintCmd.replace(/"/g, '\\"')}"
${stack.lintCmd}
if [ $? -ne 0 ]; then
  echo "✖ Lint checks failed. Commit aborted."
  exit 1
fi

echo "🛡️  Running Typecheck: ${stack.typecheckCmd.replace(/"/g, '\\"')}"
${stack.typecheckCmd}
if [ $? -ne 0 ]; then
  echo "✖ Typecheck failed. Commit aborted."
  exit 1
fi

echo "✅ [OpenGuild] All verification invariants passed!"
exit 0
`;

  const hookPath = path.join(hooksDir, 'pre-commit');
  fs.writeFileSync(hookPath, hookScript, 'utf8');

  if (process.platform !== 'win32') {
    try {
      fs.chmodSync(hookPath, 0o755);
    } catch { /* ignore */ }
  }

  console.log(`${c.green}✅ [Installed]${c.reset} Pre-commit invariant hook at: ${c.dim}${hookPath}${c.reset}`);
  console.log(`   Enforces: ${c.bold}${stack.testCmd}${c.reset} | ${c.bold}${stack.lintCmd}${c.reset} | ${c.bold}${stack.typecheckCmd}${c.reset}`);
  return true;
}

module.exports = {
  installPreCommitHook,
};
